# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "check"
client_id = "fb0ee5d612939ec1b4bc1d9acf80ce55"
application_url = "https://buf-michigan-dictionary-review.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://buf-michigan-dictionary-review.trycloudflare.com/auth/callback",
  "https://buf-michigan-dictionary-review.trycloudflare.com/auth/shopify/callback",
  "https://buf-michigan-dictionary-review.trycloudflare.com/api/auth/callback",
  "https://buf-michigan-dictionary-review.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "autoseo2.myshopify.com"
